const fs = require("fs");
const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  Header, Footer, AlignmentType, LevelFormat,
  TableOfContents, HeadingLevel, BorderStyle, WidthType, ShadingType,
  PageNumber, PageBreak
} = require("docx");

// ─── helpers ────────────────────────────────────────────────────────────────
const heading1 = (text) => new Paragraph({ heading: HeadingLevel.HEADING_1, spacing: { before: 360, after: 200 }, children: [new TextRun({ text, bold: true, size: 32, font: "Arial" })] });
const heading2 = (text) => new Paragraph({ heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 160 }, children: [new TextRun({ text, bold: true, size: 28, font: "Arial" })] });
const heading3 = (text) => new Paragraph({ heading: HeadingLevel.HEADING_3, spacing: { before: 240, after: 120 }, children: [new TextRun({ text, bold: true, size: 24, font: "Arial" })] });
const heading4 = (text) => new Paragraph({ spacing: { before: 200, after: 100 }, children: [new TextRun({ text, bold: true, size: 22, font: "Arial" })] });

const para = (text, opts = {}) => new Paragraph({ spacing: { after: 120 }, ...opts, children: [new TextRun({ text, size: 22, font: "Arial", ...opts })] });
const emptyLine = () => new Paragraph({ spacing: { after: 80 }, children: [] });

const placeholder = (desc) => new Paragraph({
  spacing: { after: 120 },
  children: [new TextRun({ text: `[${desc}]`, size: 22, font: "Arial", italics: true, color: "888888" })]
});

const bold = (text) => new TextRun({ text, bold: true, size: 22, font: "Arial" });
const normal = (text) => new TextRun({ text, size: 22, font: "Arial" });

const mixedPara = (runs) => new Paragraph({ spacing: { after: 120 }, children: runs });

// ─── table helpers ──────────────────────────────────────────────────────────
const border = { style: BorderStyle.SINGLE, size: 1, color: "999999" };
const borders = { top: border, bottom: border, left: border, right: border };
const cellMargins = { top: 60, bottom: 60, left: 100, right: 100 };

function makeCell(text, width, shading, isBold = false) {
  return new TableCell({
    borders, width: { size: width, type: WidthType.DXA },
    shading: shading ? { fill: shading, type: ShadingType.CLEAR } : undefined,
    margins: cellMargins,
    children: [new Paragraph({ children: [new TextRun({ text, size: 20, font: "Arial", bold: isBold })] })]
  });
}

// ─── page break ─────────────────────────────────────────────────────────────
const pageBreak = () => new Paragraph({ children: [new PageBreak()] });

// ═══════════════════════════════════════════════════════════════════════════
//  DOCUMENT CONTENT
// ═══════════════════════════════════════════════════════════════════════════

const coverPage = [
  emptyLine(), emptyLine(), emptyLine(), emptyLine(), emptyLine(),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 }, children: [new TextRun({ text: "ASIA PACIFIC UNIVERSITY OF TECHNOLOGY & INNOVATION", size: 28, font: "Arial", bold: true })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 400 }, children: [new TextRun({ text: "SCHOOL OF COMPUTING", size: 24, font: "Arial" })] }),
  emptyLine(), emptyLine(),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 200 }, children: [new TextRun({ text: "CINEMA TICKET BOOKING SYSTEM", size: 36, font: "Arial", bold: true })] }),
  emptyLine(),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 120 }, children: [new TextRun({ text: "AAPP013-4-2 Object Oriented Programming", size: 24, font: "Arial" })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 120 }, children: [new TextRun({ text: "Group Assignment", size: 24, font: "Arial" })] }),
  emptyLine(), emptyLine(), emptyLine(),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 120 }, children: [new TextRun({ text: "Prepared by:", size: 22, font: "Arial", bold: true })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 80 }, children: [new TextRun({ text: "[Student 1 Name] - [TP Number]", size: 22, font: "Arial" })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 80 }, children: [new TextRun({ text: "[Student 2 Name] - [TP Number]", size: 22, font: "Arial" })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 80 }, children: [new TextRun({ text: "[Student 3 Name] - [TP Number]", size: 22, font: "Arial" })] }),
  emptyLine(), emptyLine(),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 120 }, children: [new TextRun({ text: "Lecturer: [Lecturer Name]", size: 22, font: "Arial" })] }),
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { after: 120 }, children: [new TextRun({ text: "Submission Date: 3 April 2026", size: 22, font: "Arial" })] }),
  pageBreak(),
];

// ─── TOC ────────────────────────────────────────────────────────────────────
const tocSection = [
  heading1("Table of Contents"),
  new TableOfContents("Table of Contents", { hyperlink: true, headingStyleRange: "1-3" }),
  para("(Right-click and select 'Update Field' in Word to refresh the table of contents.)"),
  pageBreak(),
];

// ─── Assumptions ────────────────────────────────────────────────────────────
const assumptions = [
  heading1("Assumptions"),
  para("The following assumptions were made during the development of this Cinema Ticket Booking System:"),
  emptyLine(),
  para("1. All data is stored in text files (.txt) using pipe-delimited format. No database system is used."),
  para("2. The system supports three user roles: Cinema Manager, Ticketing Clerk, and Customer."),
  para("3. Default credentials are pre-loaded in the users.txt file for the Manager (admin/admin123) and Ticketing Clerk (clerk1/clerk123) accounts."),
  para("4. Customers can register their own accounts through the registration page."),
  para("5. Each showtime has a fixed seating layout of 5 rows (A-E) and 10 columns, totalling 50 seats per screening."),
  para("6. Rows A-C are classified as STANDARD seats and rows D-E are classified as PREMIUM seats."),
  para("7. Walk-in customers do not require an account. Their bookings are recorded with the user ID 'WALK-IN'."),
  para("8. Three discount categories are available: Student (10%), Senior Citizen (15%), and Child (20%). These percentages can be updated by the Manager."),
  para("9. Payment methods supported are Cash and Card. No actual payment gateway is integrated."),
  para("10. The system is designed as a standalone desktop application using Java Swing GUI."),
  para("11. The application is built using Apache NetBeans IDE with the Ant build system."),
  para("12. Movie deletion is a soft delete (sets isActive to false) to preserve data integrity for existing bookings."),
  pageBreak(),
];

// ─── 1.0 Introduction ──────────────────────────────────────────────────────
const introduction = [
  heading1("1.0 Introduction"),
  para("This project is a Cinema Ticket Booking System developed as a group assignment for the Object Oriented Programming module (AAPP013-4-2). The system is a standalone Java Swing desktop application that allows three types of users to interact with a cinema booking platform."),
  emptyLine(),
  para("The Cinema Manager is responsible for managing movie listings, creating and editing showtimes and screening schedules, setting ticket prices and configuring discount policies, and viewing booking reports with revenue summaries."),
  emptyLine(),
  para("The Ticketing Clerk handles walk-in customer bookings, can view and cancel existing bookings, view seating availability, and process payments with receipt generation."),
  emptyLine(),
  para("Customers can register an account, browse currently showing movies, book tickets online by selecting seats, view their booking history, cancel bookings, and update their profile information."),
  emptyLine(),
  para("All data is persisted using pipe-delimited text files (users.txt, movies.txt, showtimes.txt, bookings.txt, seats.txt, payments.txt, and discounts.txt). The system implements core object-oriented concepts including inheritance, polymorphism, encapsulation, interfaces, abstract classes, and exception handling. The GUI is built entirely with Java Swing components."),
  pageBreak(),
];

// ─── 1.1 Sample User Flow - Ticketing Clerk ─────────────────────────────────
const flow_clerk = [
  heading2("1.1 Sample User Flow of Ticketing Clerk ([Student 1 Name])"),
  para("For a ticketing clerk, they will first access the system through the login frame UI (LoginFrame.java). In this case, we will use the default credentials that are hardcoded into our system, which is clerk1 for username and clerk123 for password that can be found in users.txt file under the data folder."),
  emptyLine(),
  placeholder("SCREENSHOT: Login UI with clerk1 credentials entered"),
  para("Image 1.1.1: Login UI.", { italics: true }),
  emptyLine(),
  para("Once that is done, the ticketing clerk will click login which will invoke the ticketing clerk dashboard (ClerkDashboard.java). In this user interface, the ticketing clerk will be given four options of buttons. These are three function classes which will be invoked once clicked, and one logout button. One subtle detail design-wise is that the system will welcome the ticketing clerk by their name as shown in the dashboard."),
  emptyLine(),
  placeholder("SCREENSHOT: Clerk Dashboard with welcome message and 4 buttons"),
  para("Image 1.1.2: Clerk Dashboard.", { italics: true }),
  emptyLine(),
  para("When a customer walks in to book tickets for a movie, the ticketing clerk will click the first button which will invoke the walk-in booking panel (ClerkBookingPanel.java). In this UI, the clerk will be able to select the respective movie, showtime, discount and payment method. All of which will be a dropdown menu (JComboBox) which reads from their data txt files respectively."),
  emptyLine(),
  placeholder("SCREENSHOT: Walk-in Booking Interface with dropdown menus"),
  para("Image 1.1.3: Walk-in Booking Interface.", { italics: true }),
  emptyLine(),
  para("In this case, we will select a movie, showtime, apply a discount category, select cash payment and enter a customer name. One thing to take note of is that the customer name is not actually used for user ID purposes and is saved as 'WALK-IN' for their user ID."),
  emptyLine(),
  placeholder("SCREENSHOT: Walk-in Booking with options selected"),
  para("Image 1.1.4: Selecting Options.", { italics: true }),
  emptyLine(),
  para("The seat selection panel (SeatSelectionPanel.java) allows the clerk to visually select available seats from a 5x10 grid. Green seats are available, blue seats are selected, and red/disabled seats are already booked."),
  emptyLine(),
  placeholder("SCREENSHOT: Seat Selection Panel with some seats selected"),
  para("Image 1.1.5: Seat Selection.", { italics: true }),
  emptyLine(),
  para("Once all that is done, we will click the calculate button to let the customer view the price before confirming."),
  emptyLine(),
  placeholder("SCREENSHOT: Price calculation shown"),
  para("Image 1.1.6: Calculate Demo.", { italics: true }),
  emptyLine(),
  para("After that, we can proceed by clicking the 'Book & Pay' button. It will first show a confirmation dialog and once we click 'YES', the receipt will be generated and displayed in a ReceiptDialog."),
  emptyLine(),
  placeholder("SCREENSHOT: Confirmation dialog"),
  para("Image 1.1.7: Booking Confirmation.", { italics: true }),
  emptyLine(),
  placeholder("SCREENSHOT: Receipt dialog showing booking details"),
  para("Image 1.1.8: Receipt.", { italics: true }),
  emptyLine(),
  para("The clerk can also manage bookings through the 'Manage Bookings' button (ClerkManageBookingsPanel.java) which shows all bookings in a table, with the ability to cancel bookings. The 'View Screenings' button (ClerkScreeningsPanel.java) shows available showtimes and seat availability."),
  emptyLine(),
  placeholder("SCREENSHOT: Manage Bookings Panel with booking table"),
  para("Image 1.1.9: Manage Bookings.", { italics: true }),
  emptyLine(),
  placeholder("SCREENSHOT: View Screenings Panel"),
  para("Image 1.1.10: View Screenings.", { italics: true }),
  emptyLine(),
  para("Demonstrating wrong input: If the clerk tries to book without selecting a showtime or seats, error messages will appear."),
  emptyLine(),
  placeholder("SCREENSHOT: Error message when booking with no seats selected"),
  para("Image 1.1.11: Error Handling - No Seats Selected.", { italics: true }),
  emptyLine(),
  placeholder("SCREENSHOT: Error message for invalid input"),
  para("Image 1.1.12: Error Handling - Invalid Input.", { italics: true }),
  pageBreak(),
];

// ─── 1.2 Sample User Flow - Manager ─────────────────────────────────────────
const flow_manager = [
  heading2("1.2 Sample User Flow of Cinema Manager ([Student 2 Name])"),
  para("The cinema manager will access the system through the same login frame (LoginFrame.java). The default credentials for the manager are admin for username and admin123 for password."),
  emptyLine(),
  placeholder("SCREENSHOT: Login UI with admin credentials entered"),
  para("Image 1.2.1: Manager Login.", { italics: true }),
  emptyLine(),
  para("After successful login, the manager dashboard (ManagerDashboard.java) is displayed with five options: Manage Movies, Manage Showtimes, Manage Pricing, View Reports, and Logout."),
  emptyLine(),
  placeholder("SCREENSHOT: Manager Dashboard"),
  para("Image 1.2.2: Manager Dashboard.", { italics: true }),
  emptyLine(),
  para("Clicking 'Manage Movies' opens ManageMoviesPanel.java. The manager can add new movies by filling in the title, genre, duration, language, rating, and description, then clicking 'Add Movie'. Existing movies are shown in a table."),
  emptyLine(),
  placeholder("SCREENSHOT: Manage Movies Panel with movie list"),
  para("Image 1.2.3: Manage Movies Panel.", { italics: true }),
  emptyLine(),
  para("To update a movie, the manager clicks on a row in the table which populates the form fields. After editing, the 'Update Movie' button saves the changes. To delete a movie, the manager selects it and clicks 'Delete Movie' which performs a soft delete."),
  emptyLine(),
  placeholder("SCREENSHOT: Adding a new movie"),
  para("Image 1.2.4: Adding a Movie.", { italics: true }),
  emptyLine(),
  placeholder("SCREENSHOT: Updating an existing movie"),
  para("Image 1.2.5: Updating a Movie.", { italics: true }),
  emptyLine(),
  placeholder("SCREENSHOT: Delete confirmation dialog"),
  para("Image 1.2.6: Deleting a Movie.", { italics: true }),
  emptyLine(),
  para("The 'Manage Showtimes' panel (ManageShowtimesPanel.java) allows the manager to create new showtimes by selecting a movie, hall, date, time, and base price. When a showtime is created, 50 seats are automatically initialized (BookingService.java). The manager can also update or delete existing showtimes."),
  emptyLine(),
  placeholder("SCREENSHOT: Manage Showtimes Panel"),
  para("Image 1.2.7: Manage Showtimes.", { italics: true }),
  emptyLine(),
  placeholder("SCREENSHOT: Adding a new showtime"),
  para("Image 1.2.8: Adding a Showtime.", { italics: true }),
  emptyLine(),
  para("In the 'Manage Pricing' panel (ManagePricingPanel.java), the manager can configure discount percentages for three categories: Senior Citizen, Student, and Child. The values are read from and saved to discounts.txt."),
  emptyLine(),
  placeholder("SCREENSHOT: Manage Pricing Panel with discount fields"),
  para("Image 1.2.9: Manage Pricing.", { italics: true }),
  emptyLine(),
  para("The 'View Reports' panel (ReportsPanel.java) displays all bookings in a table with details including movie name, hall, date/time, seats, amount, and status. Summary statistics show total bookings, total revenue, confirmed count, and cancelled count."),
  emptyLine(),
  placeholder("SCREENSHOT: Reports Panel with booking table and summary"),
  para("Image 1.2.10: Booking Reports.", { italics: true }),
  emptyLine(),
  para("Demonstrating wrong input: If the manager tries to add a movie without filling in required fields, or enters an invalid duration, error messages are shown."),
  emptyLine(),
  placeholder("SCREENSHOT: Error when adding movie with empty fields"),
  para("Image 1.2.11: Error Handling - Empty Fields.", { italics: true }),
  emptyLine(),
  placeholder("SCREENSHOT: Error when entering invalid number for duration"),
  para("Image 1.2.12: Error Handling - Invalid Duration.", { italics: true }),
  pageBreak(),
];

// ─── 1.3 Sample User Flow - Customer ────────────────────────────────────────
const flow_customer = [
  heading2("1.3 Sample User Flow of Customer ([Student 3 Name])"),
  para("A new customer will first register through the registration page (RegisterFrame.java) which is accessed by clicking 'Register' on the login screen. The customer needs to provide a username, password, confirm password, full name, email, and phone number."),
  emptyLine(),
  placeholder("SCREENSHOT: Registration page with fields filled in"),
  para("Image 1.3.1: Customer Registration.", { italics: true }),
  emptyLine(),
  para("After successful registration, the customer can log in using their credentials. The system authenticates via AuthService.java and redirects to the Customer Dashboard (CustomerDashboard.java)."),
  emptyLine(),
  placeholder("SCREENSHOT: Login with customer credentials"),
  para("Image 1.3.2: Customer Login.", { italics: true }),
  emptyLine(),
  placeholder("SCREENSHOT: Customer Dashboard"),
  para("Image 1.3.3: Customer Dashboard.", { italics: true }),
  emptyLine(),
  para("Clicking 'Browse Movies' opens CustomerMoviesPanel.java which displays all active movies in a table. The customer can select a movie and click 'Book Tickets' to proceed."),
  emptyLine(),
  placeholder("SCREENSHOT: Browse Movies panel with movie list"),
  para("Image 1.3.4: Browse Movies.", { italics: true }),
  emptyLine(),
  para("The booking panel (BookingPanel.java) lets the customer select a showtime from a dropdown, pick seats from the visual 5x10 seat grid, choose a discount category, and select a payment method. The system calculates the total price based on the base price, number of seats, and any applied discount."),
  emptyLine(),
  placeholder("SCREENSHOT: Booking Panel with showtime selected"),
  para("Image 1.3.5: Booking Panel.", { italics: true }),
  emptyLine(),
  placeholder("SCREENSHOT: Seat selection with seats chosen"),
  para("Image 1.3.6: Selecting Seats.", { italics: true }),
  emptyLine(),
  placeholder("SCREENSHOT: Price calculated with discount applied"),
  para("Image 1.3.7: Price Calculation.", { italics: true }),
  emptyLine(),
  para("After confirming, the booking is created and a receipt is generated and displayed."),
  emptyLine(),
  placeholder("SCREENSHOT: Booking receipt"),
  para("Image 1.3.8: Booking Receipt.", { italics: true }),
  emptyLine(),
  para("The 'My Bookings' panel (CustomerBookingsPanel.java) shows all bookings for the logged-in customer. From here, the customer can cancel a booking (which frees the seats) or view the receipt for a confirmed booking."),
  emptyLine(),
  placeholder("SCREENSHOT: My Bookings panel showing booking list"),
  para("Image 1.3.9: My Bookings.", { italics: true }),
  emptyLine(),
  placeholder("SCREENSHOT: Cancel booking confirmation"),
  para("Image 1.3.10: Cancelling a Booking.", { italics: true }),
  emptyLine(),
  para("The 'Edit Profile' panel (CustomerProfilePanel.java) allows the customer to update their full name, email, phone number, and password."),
  emptyLine(),
  placeholder("SCREENSHOT: Edit Profile panel"),
  para("Image 1.3.11: Edit Profile.", { italics: true }),
  emptyLine(),
  para("Demonstrating wrong input: If the customer tries to register with an existing username, mismatched passwords, or empty required fields, validation errors are shown."),
  emptyLine(),
  placeholder("SCREENSHOT: Registration error - username exists"),
  para("Image 1.3.12: Error - Username Already Exists.", { italics: true }),
  emptyLine(),
  placeholder("SCREENSHOT: Registration error - password mismatch"),
  para("Image 1.3.13: Error - Password Mismatch.", { italics: true }),
  emptyLine(),
  placeholder("SCREENSHOT: Booking error - no seats selected"),
  para("Image 1.3.14: Error - No Seats Selected.", { italics: true }),
  pageBreak(),
];

// ═══════════════════════════════════════════════════════════════════════════
//  SECTION 2 - OO Concepts and Java Features
// ═══════════════════════════════════════════════════════════════════════════

const section2_1 = [
  heading1("2.0 Object-Oriented Concepts and Java Features"),
  heading2("2.1 Ticketing Clerk ([Student 1 Name])"),
  heading3("2.1.1 Java Features"),

  heading4("2.1.1.1 Displaying and Reading Text"),
  para("The system reads text from .txt files line by line using BufferedReader and displays information to the user through Swing components such as JLabel, JTable and JTextArea."),
  emptyLine(),
  para("Reading text from file - FileHandler.java (lines 17-31):"),
  placeholder("CODE SCREENSHOT: FileHandler.java (lines 17-31) - readLines method with BufferedReader"),
  emptyLine(),
  para("Displaying text in the UI - ClerkDashboard.java (lines 19-20):"),
  placeholder("CODE SCREENSHOT: ClerkDashboard.java (lines 19-20) - setTitle and welcome label"),
  emptyLine(),
  para("Formatted text output for receipt - PaymentService.java (lines 80-102):"),
  placeholder("CODE SCREENSHOT: PaymentService.java (lines 80-102) - StringBuilder receipt generation"),
  emptyLine(),

  heading4("2.1.1.2 Variables and Data Types"),
  para("The system uses a range of Java primitive and reference data types across the model and service classes."),
  emptyLine(),
  para("Primitive types and reference types - TicketingClerk.java (lines 9-11) and Booking.java (lines 9-16):"),
  placeholder("CODE SCREENSHOT: TicketingClerk.java (lines 9-11) - private fields (String, int types)"),
  placeholder("CODE SCREENSHOT: Booking.java (lines 9-16) - private fields (String, double, int types)"),
  emptyLine(),
  para("Local variables - BookingService.java (lines 44-53):"),
  placeholder("CODE SCREENSHOT: BookingService.java (lines 44-53) - local variable declarations"),
  emptyLine(),

  heading4("2.1.1.3 Comments"),
  para("We use single-line (//) and Javadoc comments to explain method intent or documentation."),
  emptyLine(),
  para("Inline single-line comments - BookingService.java:"),
  placeholder("CODE SCREENSHOT: BookingService.java - showing // comments"),
  emptyLine(),

  heading4("2.1.1.4 Conditional Construct"),
  para("Conditional (if, switch, ternary) statements are used throughout the codebase for validation, business logic and displaying status."),
  emptyLine(),
  para("if-else from ClerkManageBookingsPanel.java (lines 133-155) - Cancel booking validation:"),
  placeholder("CODE SCREENSHOT: ClerkManageBookingsPanel.java (lines 133-155) - if-else chain for booking cancellation"),
  emptyLine(),
  para("switch statement from ClerkBookingPanel.java (lines 237-248) - discount category:"),
  placeholder("CODE SCREENSHOT: ClerkBookingPanel.java (lines 237-248) - switch for discount selection"),
  emptyLine(),
  para("Ternary operator from SeatSelectionPanel.java (line 29):"),
  placeholder("CODE SCREENSHOT: SeatSelectionPanel.java (line 29) - ternary operator for seat type"),
  emptyLine(),

  heading4("2.1.1.5 Iterative Construct"),
  para("while loop - Reading every line of a file until end, from FileHandler.java (lines 24-29):"),
  placeholder("CODE SCREENSHOT: FileHandler.java (lines 24-29) - while loop with readLine()"),
  emptyLine(),
  para("for loop - Building the seat grid, from SeatSelectionPanel.java (lines 39-64):"),
  placeholder("CODE SCREENSHOT: SeatSelectionPanel.java (lines 39-64) - nested for loop building seat grid"),
  emptyLine(),
  para("Collecting selected seats, from SeatSelectionPanel.java (lines 115-122):"),
  placeholder("CODE SCREENSHOT: SeatSelectionPanel.java (lines 115-122) - for loop collecting selections"),
  emptyLine(),
  para("for-each loop - Loading movies into combo box, from ClerkBookingPanel.java (lines 193-196):"),
  placeholder("CODE SCREENSHOT: ClerkBookingPanel.java (lines 193-196) - for-each with movie list"),
  emptyLine(),
  para("Loading bookings into JTable, from ClerkManageBookingsPanel.java (lines 113-126):"),
  placeholder("CODE SCREENSHOT: ClerkManageBookingsPanel.java (lines 113-126) - for-each populating table"),
  emptyLine(),
  para("Marking seats as booked, from BookingService.java (lines 32-36):"),
  placeholder("CODE SCREENSHOT: BookingService.java (lines 32-36) - for-each updating seat status"),
  emptyLine(),

  heading4("2.1.1.6 Arrays"),
  para("Single-dimensional (1D) arrays:"),
  emptyLine(),
  para("Row label constant array - SeatSelectionPanel.java (line 21):"),
  placeholder("CODE SCREENSHOT: SeatSelectionPanel.java (line 21) - String[] ROW_LABELS"),
  emptyLine(),
  para("Seat row array used for initialization - BookingService.java (line 146):"),
  placeholder("CODE SCREENSHOT: BookingService.java (line 146) - String[] rows"),
  emptyLine(),
  para("Splitting comma-separated seat numbers - BookingService.java (lines 67-68):"),
  placeholder("CODE SCREENSHOT: BookingService.java (lines 67-68) - String[] from split"),
  emptyLine(),
  para("Table column header array - ClerkManageBookingsPanel.java (lines 52-53):"),
  placeholder("CODE SCREENSHOT: ClerkManageBookingsPanel.java (lines 52-53) - column header array"),
  emptyLine(),
  para("Multidimensional (2D) arrays:"),
  emptyLine(),
  para("5x10 seat button grid - SeatSelectionPanel.java (lines 17-24):"),
  placeholder("CODE SCREENSHOT: SeatSelectionPanel.java (lines 17-24) - JToggleButton[][] seatButtons"),
  emptyLine(),
  para("Reading from the 2D array - SeatSelectionPanel.java (lines 91-108):"),
  placeholder("CODE SCREENSHOT: SeatSelectionPanel.java (lines 91-108) - iterating over 2D array"),
  emptyLine(),

  heading4("2.1.1.7 String Handling"),
  para("Strings are heavily manipulated throughout the codebase for serialization, parsing, display and formatting."),
  emptyLine(),
  para("String concatenation and String.format - Booking.java (lines 35-37):"),
  placeholder("CODE SCREENSHOT: Booking.java (lines 35-37) - getDisplayInfo()"),
  emptyLine(),
  para("String.join() - BookingService.java (line 50):"),
  placeholder("CODE SCREENSHOT: BookingService.java (line 50) - String.join"),
  emptyLine(),
  para("String.split() - FileHandler.java (lines 39-40):"),
  placeholder("CODE SCREENSHOT: FileHandler.java (lines 39-40) - line.split"),
  emptyLine(),
  para("StringBuilder for receipt - PaymentService.java (lines 80-102):"),
  placeholder("CODE SCREENSHOT: PaymentService.java (lines 80-102) - StringBuilder"),
  para("StringBuilder is more efficient than '+' concatenation when building many strings in a loop or sequence."),
  emptyLine(),
  para("String.startsWith() and Integer.parseInt() - FileHandler.java (lines 101-107):"),
  placeholder("CODE SCREENSHOT: FileHandler.java (lines 101-107) - startsWith and parseInt"),
  emptyLine(),

  heading4("2.1.1.8 Type Casting and Type Conversion"),
  para("Parsing String to double - Booking.java (line 56):"),
  placeholder("CODE SCREENSHOT: Booking.java (line 56) - Double.parseDouble()"),
  emptyLine(),
  para("Parsing String to int - Showtime.java (lines 54-55):"),
  placeholder("CODE SCREENSHOT: Showtime.java (lines 54-55) - Integer.parseInt()"),
  emptyLine(),
  para("Parsing String to boolean - Seat.java (line 46):"),
  placeholder("CODE SCREENSHOT: Seat.java (line 46) - Boolean.parseBoolean()"),
  emptyLine(),
  para("Casting Object from event source - SeatSelectionPanel.java (line 56):"),
  placeholder("CODE SCREENSHOT: SeatSelectionPanel.java (line 56) - (JToggleButton) e.getSource()"),
  para("e.getSource() returns Object and it is explicitly cast to JToggleButton to call setBackground()."),
  emptyLine(),
  para("Casting table cell value - ClerkManageBookingsPanel.java (lines 138, 148):"),
  placeholder("CODE SCREENSHOT: ClerkManageBookingsPanel.java (lines 138, 148) - table cell casting"),
  emptyLine(),

  heading4("2.1.1.9 Exception Handling"),
  para("Declaring and Throwing Exceptions:"),
  para("Service method declaring checked exception - BookingService.java (lines 21-27):"),
  placeholder("CODE SCREENSHOT: BookingService.java (lines 21-27) - throws Exception"),
  emptyLine(),
  para("Throwing exception for invalid login - AuthService.java (line 26):"),
  placeholder("CODE SCREENSHOT: AuthService.java (line 26) - throw new Exception"),
  emptyLine(),
  para("Catching Exceptions:"),
  para("try-catch block - ClerkBookingPanel.java (lines 281-308):"),
  placeholder("CODE SCREENSHOT: ClerkBookingPanel.java (lines 281-308) - try-catch"),
  emptyLine(),
  para("Multi-catch - ClerkDashboard.java (lines 138-139):"),
  placeholder("CODE SCREENSHOT: ClerkDashboard.java (lines 138-139) - multi-catch"),
  emptyLine(),
  para("Try-with-resources - FileHandler.java (lines 23-29):"),
  placeholder("CODE SCREENSHOT: FileHandler.java (lines 23-29) - try-with-resources"),
  emptyLine(),

  heading4("2.1.1.10 Static Members and Methods"),
  para("Static fields and methods belong to the class itself, not to any instance. FileHandler.java is a pure utility class using only static methods."),
  emptyLine(),
  para("Static constants - FileHandler.java (line 14) and BookingService.java (lines 16-18):"),
  placeholder("CODE SCREENSHOT: FileHandler.java (line 14) and BookingService.java (lines 16-18) - static final constants"),
  emptyLine(),
  para("Static utility methods - FileHandler.java (lines 17, 35, 48, 59, 68, 83, 96):"),
  placeholder("CODE SCREENSHOT: FileHandler.java - static method signatures"),
  emptyLine(),
  para("Static factory method - TicketingClerk.java (lines 42-46):"),
  placeholder("CODE SCREENSHOT: TicketingClerk.java (lines 42-46) - fromFileString()"),
  para("Static factory methods allow object creation from stored data without needing an existing instance."),
  emptyLine(),
  para("Static logger - ClerkDashboard.java (line 12):"),
  placeholder("CODE SCREENSHOT: ClerkDashboard.java (line 12) - Logger"),
  emptyLine(),

  heading4("2.1.1.11 Access Modifiers"),
  para("A variety of access modifiers such as private, public, static and final were used in the codebase."),
  emptyLine(),
  para("Example from Booking.java:"),
  placeholder("CODE SCREENSHOT: Booking.java - private fields, public methods, static methods"),
  emptyLine(),

  heading4("2.1.1.12 Collections (ArrayList and List)"),
  para("The java.util.List interface and java.util.ArrayList implementation are used throughout to hold sets of model objects returned from file reads."),
  emptyLine(),
  para("Declaring and using a List - ClerkBookingPanel.java (lines 24, 32):"),
  placeholder("CODE SCREENSHOT: ClerkBookingPanel.java (lines 24, 32) - List declaration"),
  emptyLine(),
  para("List returned from service - BookingService.java (lines 112-119):"),
  placeholder("CODE SCREENSHOT: BookingService.java (lines 112-119) - returning List<Booking>"),
  emptyLine(),
  para("Checking list size - ClerkBookingPanel.java (lines 252-259):"),
  placeholder("CODE SCREENSHOT: ClerkBookingPanel.java (lines 252-259) - list.size() and list.get()"),
  emptyLine(),

  heading3("2.1.2 Object-Oriented Concepts"),

  heading4("2.1.2.1 Classes and Objects"),
  para("A class is a blueprint defining fields and behaviors. An object is a runtime instance created from that blueprint using the 'new' keyword."),
  emptyLine(),
  para("Class definition - TicketingClerk.java (line 8):"),
  placeholder("CODE SCREENSHOT: TicketingClerk.java (line 8) - class declaration"),
  emptyLine(),
  para("Creating objects - ClerkDashboard.java (lines 113-122):"),
  placeholder("CODE SCREENSHOT: ClerkDashboard.java (lines 113-122) - new panel objects"),
  emptyLine(),
  para("Object instantiation in service - BookingService.java (lines 52-53):"),
  placeholder("CODE SCREENSHOT: BookingService.java (lines 52-53) - new Booking()"),
  emptyLine(),

  heading4("2.1.2.2 Encapsulation"),
  para("Encapsulation bundles data (fields) and behaviour (methods) into a class and restricts direct access to fields using private. Public getters and setters provide controlled access."),
  emptyLine(),
  para("Private fields in Booking.java (lines 9-16):"),
  placeholder("CODE SCREENSHOT: Booking.java (lines 9-16) - private field declarations"),
  emptyLine(),
  para("Public getter and setter methods - Booking.java:"),
  placeholder("CODE SCREENSHOT: Booking.java - public getters/setters"),
  emptyLine(),

  heading4("2.1.2.3 Inheritance"),
  para("Inheritance allows a subclass to inherit fields and methods from a parent class using the 'extends' keyword. TicketingClerk extends the abstract User class."),
  emptyLine(),
  para("TicketingClerk.java (line 8) extending User:"),
  placeholder("CODE SCREENSHOT: TicketingClerk.java (line 8) - extends User"),
  emptyLine(),
  para("Calling parent constructor with super() - TicketingClerk.java (lines 16-21):"),
  placeholder("CODE SCREENSHOT: TicketingClerk.java (lines 16-21) - super() call"),
  emptyLine(),
  para("User.java (line 7) as the abstract parent class:"),
  placeholder("CODE SCREENSHOT: User.java (line 7) - abstract class declaration"),
  emptyLine(),

  heading4("2.1.2.4 Method Overloading"),
  para("Method overloading allows multiple methods with the same name but different parameters in the same class."),
  emptyLine(),
  para("FileHandler.readLines() has two overloaded versions - FileHandler.java (lines 17, 35):"),
  placeholder("CODE SCREENSHOT: FileHandler.java (line 17) - readLines(String filename)"),
  placeholder("CODE SCREENSHOT: FileHandler.java (line 35) - readLines(String filename, String filterValue, int fieldIndex)"),
  emptyLine(),

  heading4("2.1.2.5 Method Overriding"),
  para("Method overriding allows a subclass to provide a specific implementation for a method defined in the parent class or interface."),
  emptyLine(),
  para("TicketingClerk overriding getDashboardTitle() - TicketingClerk.java (lines 23-26):"),
  placeholder("CODE SCREENSHOT: TicketingClerk.java (lines 23-26) - @Override getDashboardTitle()"),
  emptyLine(),
  para("TicketingClerk overriding toFileString() - TicketingClerk.java (lines 33-38):"),
  placeholder("CODE SCREENSHOT: TicketingClerk.java (lines 33-38) - @Override toFileString()"),
  emptyLine(),

  heading4("2.1.2.6 Constructors"),
  para("Constructors are special methods used to initialize objects. Constructor overloading provides multiple ways to create an object."),
  emptyLine(),
  para("No-arg constructor - TicketingClerk.java (line 12):"),
  placeholder("CODE SCREENSHOT: TicketingClerk.java (line 12) - default constructor"),
  emptyLine(),
  para("Parameterized constructor - TicketingClerk.java (lines 16-21):"),
  placeholder("CODE SCREENSHOT: TicketingClerk.java (lines 16-21) - parameterized constructor with super()"),
  emptyLine(),
  pageBreak(),
];

// ─── 2.2 Cinema Manager ────────────────────────────────────────────────────
const section2_2 = [
  heading2("2.2 Cinema Manager ([Student 2 Name])"),
  heading3("2.2.1 Java Features"),

  heading4("2.2.1.1 Variables and Data Types"),
  para("The manager-related classes use various data types for storing and processing cinema data."),
  emptyLine(),
  para("Reference type variables - ManageMoviesPanel.java (lines 15-17):"),
  placeholder("CODE SCREENSHOT: ManageMoviesPanel.java (lines 15-17) - logger, movieService, tableModel"),
  emptyLine(),
  para("Service object declarations - ReportsPanel.java (lines 15-20):"),
  placeholder("CODE SCREENSHOT: ReportsPanel.java (lines 15-20) - multiple service declarations"),
  emptyLine(),
  para("Static final constant - ManagePricingPanel.java (lines 15-16):"),
  placeholder("CODE SCREENSHOT: ManagePricingPanel.java (lines 15-16) - DISCOUNTS_FILE constant"),
  emptyLine(),

  heading4("2.2.1.2 Conditional Construct"),
  para("if-else with complex condition - ManagePricingPanel.java (line 166):"),
  placeholder("CODE SCREENSHOT: ManagePricingPanel.java (line 166) - validation condition"),
  emptyLine(),
  para("switch statement - ManagePricingPanel.java (lines 149-153):"),
  placeholder("CODE SCREENSHOT: ManagePricingPanel.java (lines 149-153) - switch for discount types"),
  emptyLine(),
  para("Ternary operator - ManageMoviesPanel.java (line 206):"),
  placeholder("CODE SCREENSHOT: ManageMoviesPanel.java (line 206) - m.isIsActive() ? \"Yes\" : \"No\""),
  emptyLine(),

  heading4("2.2.1.3 Iterative Construct"),
  para("for-each loop loading movies - ManageMoviesPanel.java (lines 202-210):"),
  placeholder("CODE SCREENSHOT: ManageMoviesPanel.java (lines 202-210) - for-each loop"),
  emptyLine(),
  para("for-each loop with showtimes - ManageShowtimesPanel.java (lines 212-221):"),
  placeholder("CODE SCREENSHOT: ManageShowtimesPanel.java (lines 212-221) - for-each loop"),
  emptyLine(),
  para("for-each loop in reports - ReportsPanel.java (lines 134-160):"),
  placeholder("CODE SCREENSHOT: ReportsPanel.java (lines 134-160) - for-each with bookings"),
  emptyLine(),

  heading4("2.2.1.4 Arrays"),
  para("Column header arrays - ManageMoviesPanel.java (line 62):"),
  placeholder("CODE SCREENSHOT: ManageMoviesPanel.java (line 62) - String[] column headers"),
  emptyLine(),
  para("Hall options array - ManageShowtimesPanel.java (line 84):"),
  placeholder("CODE SCREENSHOT: ManageShowtimesPanel.java (line 84) - String[] hall options"),
  emptyLine(),
  para("String.split() producing arrays - ManagePricingPanel.java (line 148):"),
  placeholder("CODE SCREENSHOT: ManagePricingPanel.java (line 148) - split producing array"),
  emptyLine(),

  heading4("2.2.1.5 String Handling"),
  para("String.format for currency - ReportsPanel.java (lines 150, 162):"),
  placeholder("CODE SCREENSHOT: ReportsPanel.java (lines 150, 162) - String.format"),
  emptyLine(),
  para("String concatenation - ReportsPanel.java (line 143):"),
  placeholder("CODE SCREENSHOT: ReportsPanel.java (line 143) - date + time concatenation"),
  emptyLine(),
  para("String.split() with delimiter - ManageShowtimesPanel.java (line 206):"),
  placeholder("CODE SCREENSHOT: ManageShowtimesPanel.java (line 206) - split(\" - \")"),
  emptyLine(),

  heading4("2.2.1.6 Type Casting and Type Conversion"),
  para("Integer.parseInt from String input - ManagePricingPanel.java (line 162):"),
  placeholder("CODE SCREENSHOT: ManagePricingPanel.java (line 162) - Integer.parseInt()"),
  emptyLine(),
  para("toString() conversion - ManageMoviesPanel.java (line 218):"),
  placeholder("CODE SCREENSHOT: ManageMoviesPanel.java (line 218) - .toString()"),
  emptyLine(),

  heading4("2.2.1.7 Exception Handling"),
  para("try-catch with IOException - ManageMoviesPanel.java (lines 209-211):"),
  placeholder("CODE SCREENSHOT: ManageMoviesPanel.java (lines 209-211) - try-catch"),
  emptyLine(),
  para("Multiple catch clauses - ManageMoviesPanel.java (lines 234-260):"),
  placeholder("CODE SCREENSHOT: ManageMoviesPanel.java (lines 234-260) - multiple catch blocks"),
  emptyLine(),
  para("Throws declaration - MovieService.java (line 16):"),
  placeholder("CODE SCREENSHOT: MovieService.java (line 16) - throws IOException"),
  emptyLine(),

  heading4("2.2.1.8 Static Members and Methods"),
  para("Static logger - ManageMoviesPanel.java (line 15):"),
  placeholder("CODE SCREENSHOT: ManageMoviesPanel.java (line 15) - static final Logger"),
  emptyLine(),
  para("Static constants - ManagePricingPanel.java (line 16):"),
  placeholder("CODE SCREENSHOT: ManagePricingPanel.java (line 16) - static final String"),
  emptyLine(),

  heading4("2.2.1.9 Access Modifiers"),
  para("A variety of access modifiers are used in the Manager-related classes:"),
  placeholder("CODE SCREENSHOT: Manager.java - private fields, public constructors, public getters"),
  emptyLine(),

  heading4("2.2.1.10 Collections (ArrayList and List)"),
  para("List of movies from service - ManageMoviesPanel.java (line 201):"),
  placeholder("CODE SCREENSHOT: ManageMoviesPanel.java (line 201) - List<Movie>"),
  emptyLine(),
  para("ArrayList for file lines - ManagePricingPanel.java (line 171):"),
  placeholder("CODE SCREENSHOT: ManagePricingPanel.java (line 171) - new ArrayList<>()"),
  emptyLine(),

  heading4("2.2.1.11 Event Handling"),
  para("ActionListener via method reference - ManageMoviesPanel.java (lines 98-101):"),
  placeholder("CODE SCREENSHOT: ManageMoviesPanel.java (lines 98-101) - addActionListener"),
  emptyLine(),
  para("MouseAdapter for table click - ManageMoviesPanel.java (lines 68-72):"),
  placeholder("CODE SCREENSHOT: ManageMoviesPanel.java (lines 68-72) - MouseAdapter"),
  emptyLine(),

  heading4("2.2.1.12 Comments"),
  para("Javadoc comments are used for class documentation."),
  para("Javadoc from Manager.java (lines 3-6):"),
  placeholder("CODE SCREENSHOT: Manager.java (lines 3-6) - Javadoc comment"),
  emptyLine(),

  heading3("2.2.2 Object-Oriented Concepts"),

  heading4("2.2.2.1 Classes and Objects"),
  para("Manager.java (line 8) - class extending User:"),
  placeholder("CODE SCREENSHOT: Manager.java (line 8) - class Manager extends User"),
  emptyLine(),
  para("Creating panel objects - ManagerDashboard.java:"),
  placeholder("CODE SCREENSHOT: ManagerDashboard.java - new ManageMoviesPanel(), etc."),
  emptyLine(),

  heading4("2.2.2.2 Encapsulation"),
  para("Manager.java uses private fields with public getters:"),
  placeholder("CODE SCREENSHOT: Manager.java - private employeeId with getter/setter"),
  emptyLine(),

  heading4("2.2.2.3 Inheritance"),
  para("Manager extends the abstract User class, inheriting common user fields:"),
  placeholder("CODE SCREENSHOT: Manager.java (line 8, lines 16-20) - extends User with super()"),
  emptyLine(),

  heading4("2.2.2.4 Interfaces and Abstract Classes"),
  para("The User abstract class (User.java line 7) implements two interfaces: Displayable and Saveable."),
  emptyLine(),
  para("Displayable interface - Displayable.java (lines 6-8):"),
  placeholder("CODE SCREENSHOT: Displayable.java - interface definition"),
  emptyLine(),
  para("Saveable interface - Saveable.java (lines 6-7):"),
  placeholder("CODE SCREENSHOT: Saveable.java - interface definition"),
  emptyLine(),
  para("Abstract method in User.java (line 32):"),
  placeholder("CODE SCREENSHOT: User.java (line 32) - abstract getDashboardTitle()"),
  emptyLine(),

  heading4("2.2.2.5 Method Overriding"),
  para("Manager overrides abstract and interface methods:"),
  para("getDashboardTitle() - Manager.java (lines 22-25):"),
  placeholder("CODE SCREENSHOT: Manager.java (lines 22-25) - @Override getDashboardTitle()"),
  emptyLine(),
  para("getDetailedInfo() - Manager.java (lines 27-30):"),
  placeholder("CODE SCREENSHOT: Manager.java (lines 27-30) - @Override getDetailedInfo()"),
  emptyLine(),
  para("toFileString() - Manager.java (lines 32-36):"),
  placeholder("CODE SCREENSHOT: Manager.java (lines 32-36) - @Override toFileString()"),
  emptyLine(),

  heading4("2.2.2.6 Polymorphism"),
  para("Polymorphism is demonstrated in the login flow where AuthService.login() returns a User reference that could be any subclass:"),
  emptyLine(),
  para("AuthService.java (lines 62-75) - parseUser() method:"),
  placeholder("CODE SCREENSHOT: AuthService.java (lines 62-75) - switch returning different User subclasses"),
  emptyLine(),
  para("LoginFrame.java (lines 146-152) - instanceof checks:"),
  placeholder("CODE SCREENSHOT: LoginFrame.java (lines 146-152) - polymorphic dispatch"),
  emptyLine(),

  heading4("2.2.2.7 Constructors"),
  para("Manager has constructor overloading:"),
  para("No-arg constructor - Manager.java (line 12):"),
  placeholder("CODE SCREENSHOT: Manager.java (line 12) - default constructor"),
  emptyLine(),
  para("Parameterized constructor - Manager.java (lines 16-20):"),
  placeholder("CODE SCREENSHOT: Manager.java (lines 16-20) - parameterized constructor with super()"),
  emptyLine(),
  pageBreak(),
];

// ─── 2.3 Customer ───────────────────────────────────────────────────────────
const section2_3 = [
  heading2("2.3 Customer ([Student 3 Name])"),
  heading3("2.3.1 Java Features"),

  heading4("2.3.1.1 Variables and Data Types"),
  para("Customer-related classes use various primitive and reference types."),
  emptyLine(),
  para("Private fields in Customer.java (lines 9-10):"),
  placeholder("CODE SCREENSHOT: Customer.java (lines 9-10) - private String fields"),
  emptyLine(),
  para("Service declarations in BookingPanel.java (lines 17-24):"),
  placeholder("CODE SCREENSHOT: BookingPanel.java (lines 17-24) - service and UI variable declarations"),
  emptyLine(),

  heading4("2.3.1.2 Conditional Construct"),
  para("Complex validation - RegisterFrame.java (lines 159-168):"),
  placeholder("CODE SCREENSHOT: RegisterFrame.java (lines 159-168) - if conditions for validation"),
  emptyLine(),
  para("if-else for booking status - CustomerBookingsPanel.java (lines 137-148):"),
  placeholder("CODE SCREENSHOT: CustomerBookingsPanel.java (lines 137-148) - status checking"),
  emptyLine(),
  para("switch for discount - BookingPanel.java (lines 202-207):"),
  placeholder("CODE SCREENSHOT: BookingPanel.java (lines 202-207) - switch statement"),
  emptyLine(),

  heading4("2.3.1.3 Iterative Construct"),
  para("for-each loop loading showtimes - BookingPanel.java (lines 169-176):"),
  placeholder("CODE SCREENSHOT: BookingPanel.java (lines 169-176) - for-each with showtimes"),
  emptyLine(),
  para("for-each loop loading bookings - CustomerBookingsPanel.java (lines 116-132):"),
  placeholder("CODE SCREENSHOT: CustomerBookingsPanel.java (lines 116-132) - for-each with bookings"),
  emptyLine(),

  heading4("2.3.1.4 Arrays"),
  para("Column header array - CustomerBookingsPanel.java:"),
  placeholder("CODE SCREENSHOT: CustomerBookingsPanel.java - column header String array"),
  emptyLine(),
  para("String.split() producing array - BookingPanel.java (line 209):"),
  placeholder("CODE SCREENSHOT: BookingPanel.java (line 209) - split producing array"),
  emptyLine(),

  heading4("2.3.1.5 String Handling"),
  para("String.format for currency - CustomerBookingsPanel.java (line 127):"),
  placeholder("CODE SCREENSHOT: CustomerBookingsPanel.java (line 127) - String.format"),
  emptyLine(),
  para("String concatenation - CustomerBookingsPanel.java (line 123):"),
  placeholder("CODE SCREENSHOT: CustomerBookingsPanel.java (line 123) - concatenation"),
  emptyLine(),
  para("String equality - RegisterFrame.java (line 164):"),
  placeholder("CODE SCREENSHOT: RegisterFrame.java (line 164) - password.equals()"),
  emptyLine(),

  heading4("2.3.1.6 Type Casting and Type Conversion"),
  para("Password char[] to String - RegisterFrame.java (lines 152-153):"),
  placeholder("CODE SCREENSHOT: RegisterFrame.java (lines 152-153) - new String(getPassword())"),
  emptyLine(),
  para("Password field conversion - CustomerProfilePanel.java (line 146):"),
  placeholder("CODE SCREENSHOT: CustomerProfilePanel.java (line 146) - char[] to String"),
  emptyLine(),

  heading4("2.3.1.7 Exception Handling"),
  para("try-catch in booking - BookingPanel.java (lines 252-282):"),
  placeholder("CODE SCREENSHOT: BookingPanel.java (lines 252-282) - try-catch"),
  emptyLine(),
  para("try-catch in profile update - CustomerProfilePanel.java (lines 142-165):"),
  placeholder("CODE SCREENSHOT: CustomerProfilePanel.java (lines 142-165) - try-catch"),
  emptyLine(),
  para("try-catch in registration - RegisterFrame.java (lines 173-181):"),
  placeholder("CODE SCREENSHOT: RegisterFrame.java (lines 173-181) - try-catch"),
  emptyLine(),

  heading4("2.3.1.8 Static Members"),
  para("Static logger - CustomerDashboard.java (line 12):"),
  placeholder("CODE SCREENSHOT: CustomerDashboard.java (line 12) - static final Logger"),
  emptyLine(),

  heading4("2.3.1.9 Access Modifiers"),
  para("Example from Customer.java:"),
  placeholder("CODE SCREENSHOT: Customer.java - private fields, public constructor, public getters"),
  emptyLine(),

  heading4("2.3.1.10 Collections"),
  para("List of bookings - CustomerBookingsPanel.java (line 115):"),
  placeholder("CODE SCREENSHOT: CustomerBookingsPanel.java (line 115) - List<Booking>"),
  emptyLine(),
  para("List of showtimes - BookingPanel.java:"),
  placeholder("CODE SCREENSHOT: BookingPanel.java - List<Showtime>"),
  emptyLine(),

  heading4("2.3.1.11 Event Handling"),
  para("ActionListener on dashboard - CustomerDashboard.java (lines 51-64):"),
  placeholder("CODE SCREENSHOT: CustomerDashboard.java (lines 51-64) - addActionListener"),
  emptyLine(),
  para("Lambda expression - LoginFrame.java (line 22):"),
  placeholder("CODE SCREENSHOT: LoginFrame.java (line 22) - lambda ActionListener for Enter key"),
  emptyLine(),
  para("Profile update listener - CustomerProfilePanel.java (line 70):"),
  placeholder("CODE SCREENSHOT: CustomerProfilePanel.java (line 70) - addActionListener"),
  emptyLine(),

  heading4("2.3.1.12 Comments"),
  para("Javadoc comments from Customer.java (lines 2-6):"),
  placeholder("CODE SCREENSHOT: Customer.java (lines 2-6) - Javadoc comment"),
  emptyLine(),

  heading3("2.3.2 Object-Oriented Concepts"),

  heading4("2.3.2.1 Classes and Objects"),
  para("Customer.java (line 7) - class extending User:"),
  placeholder("CODE SCREENSHOT: Customer.java (line 7) - class Customer extends User"),
  emptyLine(),
  para("Creating Customer object during registration - AuthService.java (line 38):"),
  placeholder("CODE SCREENSHOT: AuthService.java (line 38) - new Customer(...)"),
  emptyLine(),

  heading4("2.3.2.2 Encapsulation"),
  para("Customer.java uses private fields with public getters and setters:"),
  placeholder("CODE SCREENSHOT: Customer.java - private fields with getter/setter"),
  emptyLine(),

  heading4("2.3.2.3 Inheritance"),
  para("Customer extends User, inheriting all common user fields and methods:"),
  placeholder("CODE SCREENSHOT: Customer.java (line 7, lines 16-22) - extends User with super()"),
  emptyLine(),

  heading4("2.3.2.4 Method Overriding"),
  para("Customer overrides getDashboardTitle() - Customer.java (lines 24-27):"),
  placeholder("CODE SCREENSHOT: Customer.java (lines 24-27) - @Override getDashboardTitle()"),
  emptyLine(),
  para("Customer overrides getDetailedInfo() - Customer.java (lines 29-32):"),
  placeholder("CODE SCREENSHOT: Customer.java (lines 29-32) - @Override getDetailedInfo()"),
  emptyLine(),
  para("Customer overrides toFileString() - Customer.java (lines 34-39):"),
  placeholder("CODE SCREENSHOT: Customer.java (lines 34-39) - @Override toFileString()"),
  emptyLine(),

  heading4("2.3.2.5 Constructors"),
  para("No-arg constructor - Customer.java (line 12):"),
  placeholder("CODE SCREENSHOT: Customer.java (line 12) - default constructor"),
  emptyLine(),
  para("Parameterized constructor - Customer.java (lines 16-22):"),
  placeholder("CODE SCREENSHOT: Customer.java (lines 16-22) - parameterized constructor with super()"),
  emptyLine(),

  heading4("2.3.2.6 Static Factory Method"),
  para("Customer.fromFileString() - Customer.java (lines 41-54):"),
  placeholder("CODE SCREENSHOT: Customer.java (lines 41-54) - static fromFileString()"),
  para("This static factory method creates a Customer object from a pipe-delimited text line read from the users.txt file."),
  emptyLine(),
  pageBreak(),
];

// ─── 3.0 Additional Features ────────────────────────────────────────────────
const additionalFeatures = [
  heading1("3.0 Additional Features"),
  para("The following additional features have been incorporated into the Cinema Ticket Booking System:"),
  emptyLine(),
  mixedPara([bold("1. Visual Seat Selection Grid: "), normal("A graphical 5x10 seat selection panel (SeatSelectionPanel.java) using JToggleButton components with colour-coded states: green for available, blue for selected, and red/disabled for booked seats.")]),
  emptyLine(),
  mixedPara([bold("2. Receipt Generation: "), normal("Automatic receipt generation (PaymentService.java) using StringBuilder that displays booking details, seat information, pricing breakdown with discounts, and payment method in a formatted dialog (ReceiptDialog.java).")]),
  emptyLine(),
  mixedPara([bold("3. Discount Management System: "), normal("A configurable discount system where the Cinema Manager can modify discount percentages for Senior Citizen, Student, and Child categories through the ManagePricingPanel. Discounts are stored in discounts.txt and applied dynamically during booking.")]),
  emptyLine(),
  mixedPara([bold("4. Booking Reports with Revenue Summary: "), normal("The ReportsPanel provides the manager with a comprehensive view of all bookings along with summary statistics including total bookings, total revenue, and counts of confirmed vs cancelled bookings.")]),
  emptyLine(),
  mixedPara([bold("5. Soft Delete for Movies: "), normal("When a movie is deleted by the manager, it is not permanently removed. Instead, the isActive field is set to false (MovieService.java), preserving data integrity for existing bookings that reference that movie.")]),
  emptyLine(),
  mixedPara([bold("6. Polymorphic User Authentication: "), normal("The login system uses polymorphism where AuthService.login() returns a User object that is dynamically dispatched to the correct dashboard based on the user's role using instanceof checks (LoginFrame.java).")]),
  emptyLine(),
  mixedPara([bold("7. Interface-based Design: "), normal("Custom interfaces Displayable and Saveable enforce consistent behaviour across all model classes, ensuring every entity can display its information and serialize to file format.")]),
  emptyLine(),
  mixedPara([bold("8. Automatic Seat Initialization: "), normal("When a new showtime is created, 50 seats (5 rows x 10 columns) are automatically initialized in seats.txt with appropriate seat types (STANDARD for rows A-C, PREMIUM for rows D-E) via BookingService.initializeSeats().")]),
  emptyLine(),
  mixedPara([bold("9. Look and Feel Customization: "), normal("The application uses the Nimbus Look and Feel (set in Main.java) for a modern appearance compared to the default Java Metal look.")]),
  emptyLine(),
  mixedPara([bold("10. Customer Profile Management: "), normal("Customers can update their personal information (name, email, phone, password) through the CustomerProfilePanel, with changes persisted to users.txt via AuthService.updateUser().")]),
  pageBreak(),
];

// ─── 4.0 Limitations ───────────────────────────────────────────────────────
const limitations = [
  heading1("4.0 Limitations"),
  para("The following are the known limitations of the Cinema Ticket Booking System:"),
  emptyLine(),
  para("1. No database integration - All data is stored in text files (.txt), which limits scalability, concurrent access, and query efficiency compared to a proper database system."),
  para("2. No actual payment processing - The system only records payment method selection (Cash or Card) but does not integrate with any real payment gateway."),
  para("3. No password encryption - User passwords are stored in plain text in users.txt, which is a security concern."),
  para("4. Single-user access - The system does not support multiple simultaneous users. If two instances modify the same text file concurrently, data corruption may occur."),
  para("5. No seat type pricing difference - Although seats are categorized as STANDARD and PREMIUM, the pricing is the same for both types based on the base price."),
  para("6. Fixed seating layout - Every showtime has a fixed 5x10 seating arrangement. The system does not support different hall sizes or seating configurations."),
  para("7. No movie search or filter functionality - Customers can only browse the full list of movies without the ability to search by title, genre, or language."),
  para("8. No email notifications - The system does not send booking confirmations or cancellation notifications via email."),
  para("9. No date validation for showtimes - The manager can create showtimes with past dates without validation."),
  para("10. Walk-in bookings have no customer tracking - Walk-in bookings use a generic 'WALK-IN' user ID, making it impossible to track individual walk-in customer history."),
  pageBreak(),
];

// ─── 5.0 Workload Matrix ───────────────────────────────────────────────────
const workloadMatrix = [
  heading1("5.0 Workload Matrix"),
  para("The following table shows the distribution of work among team members:"),
  emptyLine(),
  new Table({
    width: { size: 9360, type: WidthType.DXA },
    columnWidths: [3000, 1590, 1590, 1590, 1590],
    rows: [
      new TableRow({ children: [
        makeCell("Component", 3000, "D5E8F0", true),
        makeCell("[Student 1]", 1590, "D5E8F0", true),
        makeCell("[Student 2]", 1590, "D5E8F0", true),
        makeCell("[Student 3]", 1590, "D5E8F0", true),
        makeCell("Total", 1590, "D5E8F0", true),
      ]}),
      new TableRow({ children: [
        makeCell("Ticketing Clerk Role Functions", 3000), makeCell("[  ]%", 1590), makeCell("[  ]%", 1590), makeCell("[  ]%", 1590), makeCell("100%", 1590),
      ]}),
      new TableRow({ children: [
        makeCell("Cinema Manager Role Functions", 3000), makeCell("[  ]%", 1590), makeCell("[  ]%", 1590), makeCell("[  ]%", 1590), makeCell("100%", 1590),
      ]}),
      new TableRow({ children: [
        makeCell("Customers Role Functions", 3000), makeCell("[  ]%", 1590), makeCell("[  ]%", 1590), makeCell("[  ]%", 1590), makeCell("100%", 1590),
      ]}),
      new TableRow({ children: [
        makeCell("Assumptions", 3000), makeCell("[  ]%", 1590), makeCell("[  ]%", 1590), makeCell("[  ]%", 1590), makeCell("100%", 1590),
      ]}),
      new TableRow({ children: [
        makeCell("Screenshots & Explanations", 3000), makeCell("[  ]%", 1590), makeCell("[  ]%", 1590), makeCell("[  ]%", 1590), makeCell("100%", 1590),
      ]}),
      new TableRow({ children: [
        makeCell("OO Concepts & Java Features", 3000), makeCell("[  ]%", 1590), makeCell("[  ]%", 1590), makeCell("[  ]%", 1590), makeCell("100%", 1590),
      ]}),
      new TableRow({ children: [
        makeCell("Additional Features", 3000), makeCell("[  ]%", 1590), makeCell("[  ]%", 1590), makeCell("[  ]%", 1590), makeCell("100%", 1590),
      ]}),
    ]
  }),
  emptyLine(),
  para("* Total percentage of contribution of all members must sum up to 100% per row."),
  pageBreak(),
];

// ─── 6.0 Conclusion ────────────────────────────────────────────────────────
const conclusion = [
  heading1("6.0 Conclusion"),
  para("The Cinema Ticket Booking System has been successfully developed as a Java Swing desktop application that meets the requirements of the Object Oriented Programming assignment. The system supports three user roles (Cinema Manager, Ticketing Clerk, and Customer) with distinct functionalities for each role."),
  emptyLine(),
  para("Through the development of this system, various object-oriented programming concepts were implemented and demonstrated, including inheritance (User hierarchy with Manager, TicketingClerk, Customer subclasses), encapsulation (private fields with public getters/setters), polymorphism (AuthService login dispatching to correct dashboard), interfaces (Displayable, Saveable), abstract classes (User), method overloading (FileHandler.readLines), and method overriding (getDashboardTitle, toFileString, getDetailedInfo across all model classes)."),
  emptyLine(),
  para("Core Java features were also extensively utilized, including exception handling (try-catch, try-with-resources, throw/throws), collections (ArrayList, List), file I/O (BufferedReader, BufferedWriter), event handling (ActionListener, MouseAdapter, ItemListener), arrays (1D and 2D), string manipulation (split, format, join, StringBuilder), and type casting."),
  emptyLine(),
  para("The system demonstrates a functional cinema booking workflow with data persistence through text files, a visual seat selection interface, receipt generation, configurable discount policies, and comprehensive booking reports. While there are known limitations such as the lack of database integration and password encryption, the system fulfils the assignment requirements and serves as a practical demonstration of object-oriented programming principles in Java."),
  pageBreak(),
];

// ─── 7.0 References ────────────────────────────────────────────────────────
const references = [
  heading1("7.0 References"),
  para("Deitel, P., & Deitel, H. (2017). Java How to Program, Early Objects (11th ed.). Pearson Education."),
  emptyLine(),
  para("Oracle. (2025). The Java Tutorials. Oracle Corporation. https://docs.oracle.com/javase/tutorial/"),
  emptyLine(),
  para("Oracle. (2025). Java SE Documentation - Swing (Java Foundation Classes). Oracle Corporation. https://docs.oracle.com/javase/8/docs/technotes/guides/swing/"),
  emptyLine(),
  para("Bloch, J. (2018). Effective Java (3rd ed.). Addison-Wesley Professional."),
  pageBreak(),
];

// ─── Appendix ───────────────────────────────────────────────────────────────
const appendix = [
  heading1("Appendix"),
  para("Screenshots of all text data files used in the system:"),
  emptyLine(),
  heading2("A.1 users.txt"),
  placeholder("SCREENSHOT: Contents of src/data/users.txt"),
  emptyLine(),
  heading2("A.2 movies.txt"),
  placeholder("SCREENSHOT: Contents of src/data/movies.txt"),
  emptyLine(),
  heading2("A.3 showtimes.txt"),
  placeholder("SCREENSHOT: Contents of src/data/showtimes.txt"),
  emptyLine(),
  heading2("A.4 bookings.txt"),
  placeholder("SCREENSHOT: Contents of src/data/bookings.txt"),
  emptyLine(),
  heading2("A.5 seats.txt"),
  placeholder("SCREENSHOT: Contents of src/data/seats.txt"),
  emptyLine(),
  heading2("A.6 payments.txt"),
  placeholder("SCREENSHOT: Contents of src/data/payments.txt"),
  emptyLine(),
  heading2("A.7 discounts.txt"),
  placeholder("SCREENSHOT: Contents of src/data/discounts.txt"),
];

// ═══════════════════════════════════════════════════════════════════════════
//  ASSEMBLE DOCUMENT
// ═══════════════════════════════════════════════════════════════════════════

const doc = new Document({
  styles: {
    default: { document: { run: { font: "Arial", size: 22 } } },
    paragraphStyles: [
      { id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 32, bold: true, font: "Arial" },
        paragraph: { spacing: { before: 360, after: 200 }, outlineLevel: 0 } },
      { id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 28, bold: true, font: "Arial" },
        paragraph: { spacing: { before: 300, after: 160 }, outlineLevel: 1 } },
      { id: "Heading3", name: "Heading 3", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 24, bold: true, font: "Arial" },
        paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 2 } },
    ]
  },
  sections: [{
    properties: {
      page: {
        size: { width: 12240, height: 15840 },
        margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 }
      }
    },
    headers: {
      default: new Header({ children: [
        new Paragraph({ alignment: AlignmentType.CENTER, children: [
          new TextRun({ text: "Cinema Ticket Booking System - OOP Documentation", size: 18, font: "Arial", color: "888888" })
        ]})
      ]})
    },
    footers: {
      default: new Footer({ children: [
        new Paragraph({ alignment: AlignmentType.CENTER, children: [
          new TextRun({ text: "Page ", size: 18, font: "Arial" }),
          new TextRun({ children: [PageNumber.CURRENT], size: 18, font: "Arial" }),
        ]})
      ]})
    },
    children: [
      ...coverPage,
      ...tocSection,
      ...assumptions,
      ...introduction,
      ...flow_clerk,
      ...flow_manager,
      ...flow_customer,
      ...section2_1,
      ...section2_2,
      ...section2_3,
      ...additionalFeatures,
      ...limitations,
      ...workloadMatrix,
      ...conclusion,
      ...references,
      ...appendix,
    ]
  }]
});

// ─── Generate ───────────────────────────────────────────────────────────────
Packer.toBuffer(doc).then(buffer => {
  const outPath = "Cinema_Booking_System_Documentation.docx";
  fs.writeFileSync(outPath, buffer);
  console.log(`Documentation generated: ${outPath}`);
  console.log(`File size: ${(buffer.length / 1024).toFixed(1)} KB`);
});
